# Generated by Django 5.1.6 on 2025-03-01 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoProxy",
            fields=[],
            options={
                "verbose_name": "Published Video",
                "verbose_name_plural": "Published Videos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("videos.video",),
        ),
        migrations.AddField(
            model_name="video",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
