# Generated by Django 5.1.6 on 2025-03-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_delete_videoproxy_videoallproxy_videopublishedproxy"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="state",
            field=models.CharField(
                choices=[("PU", "Publish"), ("DR", "Draft")], default="DR", max_length=2
            ),
        ),
    ]
