# Generated by Django 5.1.6 on 2025-03-04 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0002_playlist_video"),
        ("videos", "0007_alter_video_video_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="videos",
            field=models.ManyToManyField(
                blank=True, related_name="playlist_item", to="videos.video"
            ),
        ),
        migrations.AlterField(
            model_name="playlist",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="videos.video",
            ),
        ),
    ]
