# Generated by Django 5.1.6 on 2025-03-08 19:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0002_playlist_video_playlistitem_playlist_videos"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="order",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="playlist",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="playlists.playlist",
            ),
        ),
    ]
