# Generated by Django 5.1.6 on 2025-03-08 21:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0003_playlist_order_playlist_parent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TVShowProxy",
            fields=[],
            options={
                "verbose_name": "TV Show",
                "verbose_name_plural": "TV Shows",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("playlists.playlist",),
        ),
        migrations.CreateModel(
            name="TVShowSeasonProxy",
            fields=[],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("playlists.playlist",),
        ),
        migrations.RenameField(
            model_name="playlist",
            old_name="decription",
            new_name="description",
        ),
        migrations.AlterField(
            model_name="playlist",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="playlists.playlist",
            ),
        ),
    ]
