# Generated by Django 5.1.6 on 2025-03-04 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0003_playlist_videos_alter_playlist_video"),
        ("videos", "0007_alter_video_video_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="video",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="playlist_featured",
                to="videos.video",
            ),
        ),
    ]
